microprofile/microprofile

proposals/readme.adoc
Signed-off-by: Mike Croft <mike.croft@payara.fish>
=> added MP-0005 JWT proposal links

proposals/readme.adoc
Signed-off-by: Mike Croft <mike.croft@payara.fish>
=> Fault tolerance has now been merged, remove pending approval label

proposals/readme.adoc
Signed-off-by: Mike Croft <mike.croft@payara.fish>
=> included some links to early Config API implementations

README.adoc
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
=> Fix OpenTracing name

README.adoc, pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
Updated the pom, README, and spec in prep for the 1.4 release.
=> Initial updates for 1.4 release

pom.xml, site.yaml, spec/pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/license-alv2.asciidoc, spec/src/main/asciidoc/notices.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
Making initial changes to master in preparation for the MicroProfile 2.0 release.
=> prep for 2.0 release

spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
Updating release tag references in platform 1.x spec doc.
=> Update tag refs

pom.xml, spec/pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
Tried to keep the updates to a minimum for this new MP 2.0.1 release...  Don't want to make a big deal out of this.  It's pretty minor update.
=> updated MicroProfile refs to 2.0.1

spec/src/main/asciidoc/architecture.asciidoc
I will also update the corresponding information in the Release announcement information when I put this through the Jenkins build...
=> Change micro to patch release

pom.xml, spec/src/main/asciidoc/architecture.asciidoc
Signed-off-by: Andy McCright <j.andrew.mccright@gmail.com>
Resolves #70.
=> Issue 70: Include MP Rest Client 1.2

pom.xml
Signed-off-by: Emily Jiang <emijiang@uk.ibm.com>
=> #67 include Fault Tolerance 2.0

pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>
=> Update for Metrics 2.0

pom.xml
Signed-off-by: Anthony Vanelverdinghe <anthonyv.be@outlook.com>
This fixes #95
=> Remove duplicate property opentracing-version

pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
Signed-off-by: Adam Anderson <atanderson9383@gmail.com>
=> update the MicroProfile Rest Client version to 1.3.1

pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
=> microprofile-69 Include Health Check 2.0

pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>
=> Use Metrics 2.0.0 instead of 2.0

pom.xml
=> update dependencies in pom.xml for 3.1

README.adoc, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
Signed-off-by: jclingan <jclingan@redhat.com>
=> Fixes related to MicroProfile Health and Metrics version numbers & text

CONTRIBUTING.adoc
Signed-off-by: CesarHernandezGt <chernandez@tomitribe.com>
=> Updated contributin.adoc to tackle https://github.com/eclipse/microprofile-marketing/issues/12

.gitignore, README.adoc
=> Update README.adoc to display MP version 3.2

README.adoc, faq.adoc, pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
Please review. Updated FAQ as well. Feel free to make suggestions.
=> MP 3.3 RC1

README.adoc
Signed-off-by: jclingan <jclingan@redhat.com>
The only thing left to change is the top-level README.adoc, signifying this is a final release.
=> Updated for 3.3

spec/src/main/asciidoc/architecture.asciidoc
I have already signed Eclipse Contributor Agreement and I'm part of MP mailing list.
=> Enable syntax highlighting for Maven coordinates

.gitignore, README.adoc, pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
The subject line says it all. Due to switch to Jakarta EE 8, extra diligence in the review is requested.
=> Updated for MicroProfile 4.0 and Jakarta EE 8.

README.adoc
Signed-off-by: didier <durand.didier@gmail.com>
=> fixing typo in README

CONTRIBUTING.adoc, NOTICE, README.adoc, attic/Processes/eclipse.adoc, attic/SUMMARY.adoc, attic/microprofile-spec/README.adoc, faq.adoc, pom.xml, site.yaml, spec/NOTICE, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/license-alv2.asciidoc, spec/src/main/asciidoc/microprofile-spec.asciidoc, spec/src/main/asciidoc/notices.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc, spec/src/main/resources/META-INF/NOTICE
=> Updates in preparation for the MP 4.0-RC1 release

pom.xml
=> Fix mailinglist reference

README.adoc, pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
=> Remove RC references for releasing final version of MP 4.0

README.adoc, spec/src/main/asciidoc/architecture.asciidoc
=> Update references for final release of MP 4.0

README.adoc, spec/src/main/asciidoc/architecture.asciidoc
=> Update references for release of MP 4.0-RC3

README.adoc, spec/src/main/asciidoc/architecture.asciidoc
=> Update references for release of MP 4.0-RC4

README.adoc, spec/src/main/asciidoc/architecture.asciidoc
=> Update references for release of MP 4.0 final

pom.xml
=> Remove provided scope references since they are not applicable

spec/.github/ISSUE_TEMPLATE/01-compatible-certification-request.md
=> add CCR for microprofile platform release

CONTRIBUTING.adoc, how-to-pr.adoc
=> Added detail documentation for making a PR in mp

spec/src/main/asciidoc/architecture.asciidoc
I made a few suggested minor edits such as removing a superfluous "specifications" and consistency among the use of "includes..." to more recent use of "includes:"
=> Minor edits in documentation

README.adoc, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
**Changes:**
- Update README.adoc
- Update architecture.asciidoc
- Update required-apis.asciidoc
**Checklist:** https://wiki.eclipse.org/MicroProfile/SpecRelease/Release
1. Spec release creation
Verify a spec release has been created for each new or update spec.
For missing spec releases, notify spec teams by logging a github issue on that project and, if time-sensitive, contacting directly.
2. In MicroProfile project source
NOTE: The build process will update the pom.xml <version>X.Y-SNAPSHOT</version> tags automatically, so do not manually change these.
3. Test build locally
=> Microprofile 5.0 Pre-Release 

CONTRIBUTING_es.adoc
Related to [#626](https://github.com/eclipse/microprofile-marketing/issues/626)
Signed-off-by: Emerson Castaneda <emecas@users.noreply.github.com>
=> Add Spanish version of CONTRIBUTING.adoc file

CONTRIBUTING.adoc, CONTRIBUTING_es.adoc
Related to [626](https://github.com/eclipse/microprofile-marketing/issues/626)
=> Adding navigation links connecting CONTRIBUTING pages versions

README.adoc, pom.xml, spec/pom.xml, spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/required-apis.asciidoc
This version is in draft form.
=> MicroProfile 6.0 RC1 Update

.gitignore, spec/pom.xml, spec/src/main/asciidoc/architecture.adoc, spec/src/main/asciidoc/license-efsl.adoc, spec/src/main/asciidoc/required-apis.adoc
Update the spec doc for MicroProfile 7.0 as well as updating the plugin versions
=> Update to release MP 7.0

pom.xml, spec/pom.xml
This reverts commit d52e274f1c01f34022b892f7a566ac319c7a60f9.
=> Revert "[maven-release-plugin] prepare release 7.0-RC1"

pom.xml
This reverts commit 76c6b07d9b524e7977ff7dbd2f7832dd7099edd8.
=> Revert "tidy up plugins'"
